export { LOGIN_QUERY } from './login/login'
export { SIGNUP_MUTATION } from './login/signup'
export { GET_POST } from './main/get_post'
export { CREATE_POST_MUTATION } from './main/createPost'
export { POSTS_SUBSCRIPTION } from './main/subscriptions'
export { COMMENT_MUTATION } from './main/comment'
export {PROFILE_MUTATION} from './main/editFile'
export {GET_PROFILE} from './main/getProfile'
export {GET_ID} from './main/getID'
export {SEARCH_QUERY} from './main/search'
