export { CREATE_POST_MUTATION } from './main/createPost'
export { LOGIN_QUERY } from './login/login'
export { SIGNUP_MUTATION } from './login/signup'
export { GET_POST } from './get_post'
export { POSTS_SUBSCRIPTION } from './subscriptions'
export { COMMENT_MUTATION } from './comment'
export {PROFILE_MUTATION} from './editFile'
export {GET_PROFILE} from './getProfile'
export {GET_ID} from './getID'
