export { GET_POST } from './get_post'
export { CREATE_POST_MUTATION } from './ql_main/createPost'
export { POSTS_SUBSCRIPTION } from './subscriptions'
export { COMMENT_MUTATION } from './comment'
export {PROFILE_MUTATION} from './editFile'
export {GET_PROFILE} from './getProfile'
export {GET_ID} from './getID'